import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Calendar, ArrowRight, X } from 'lucide-react';
import { useLanguage } from '../LanguageContext';
import { useSiteData } from '../data/DataContext';
function Blog() {
  const { t, lang } = useLanguage();
  const { content } = useSiteData();
  const [selected, setSelected] = useState(null);
  return <section id="blog" className="py-24 relative z-10 bg-gradient-to-b from-white/[0.02] to-transparent"><div className="container mx-auto px-6"><div className="text-center max-w-3xl mx-auto mb-16"><h2 className="text-4xl font-black mb-6 text-white">{t('blogSection.title')}</h2><div className="w-16 h-1 bg-gradient-to-r from-[#00b4db] to-[#00b09b] mx-auto rounded-full mb-6" /></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">{content.posts.map((post, i) => <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: i * 0.1 }} viewport={{ once: true }} key={post.id} className="bg-white/5 rounded-3xl overflow-hidden border border-white/10 group hover:border-[#00b4db]/50 transition-colors duration-300"><div className="h-52 overflow-hidden relative"><img src={post.img} alt="Blog Post" className="w-full h-full object-cover group-hover:scale-110 transition duration-700" /></div><div className="p-6"><div className="flex items-center gap-2 text-xs text-[#00b4db] mb-4 font-bold"><Calendar size={14} /><span>{post.date}</span></div><h3 className="text-xl font-bold mb-3 line-clamp-2">{lang === 'ar' ? post.titleAr : post.titleEn}</h3><p className="text-gray-400 text-sm leading-relaxed mb-6 line-clamp-3">{lang === 'ar' ? post.descAr : post.descEn}</p><button onClick={() => setSelected(post)} className="inline-flex items-center gap-2 text-[#00b09b] text-sm font-bold hover:gap-3 transition-all">{t('blogSection.readMore')}<ArrowRight size={16} className={lang === 'ar' ? 'rotate-180' : ''} /></button></div></motion.div>)}</div></div>{selected && <div className="fixed inset-0 z-[80] bg-black/70 backdrop-blur-sm p-4 flex items-center justify-center"><article className="bg-[#0b101e] border border-white/10 rounded-3xl max-w-2xl w-full p-6 relative"><button onClick={() => setSelected(null)} className="absolute top-4 end-4 p-2 rounded-full bg-white/10"><X /></button><img src={selected.img} className="w-full h-64 object-cover rounded-2xl mb-5" /><p className="text-[#00b4db] text-sm mb-2">{selected.date}</p><h3 className="text-3xl font-black mb-4">{lang === 'ar' ? selected.titleAr : selected.titleEn}</h3><p className="text-gray-300 leading-8">{lang === 'ar' ? selected.descAr : selected.descEn}</p></article></div>}</section>;
}
export default Blog;
